repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ --safe ]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black>=21.12b0 ]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "fix_lint" ]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.4.0
    hooks:
      - id: setup-cfg-fmt
        args: [ --min-py3-version, "3.5", "--max-py-version", "3.10" ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.7.1
  - repo: local
    hooks:
      - id: changelogs-rst
        name: changelog filenames
        language: fail
        entry: >-
          changelog files must be named
          ####.(bugfix|feature|deprecation|breaking|doc|misc).rst
        exclude: >-
          ^docs/changelog/(\d+\.(bugfix|feature|deprecation|breaking|doc|misc).rst|README.rst|template.jinja2)
        files: ^docs/changelog/
      - id: changelogs-user-role
        name: changelog files have a non-broken :user:`name` role
        language: pygrep
        entry: :user:([^`]+`?|`[^`]+[\s,])
        pass_filenames: true
        types: [file, rst]
