language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
addons:
  apt:
    packages:
    - docker-ce
script:
- make test
env:
  global:
    - GITHUB_ORG=im4do
    secure: hqq3/F51gsGFQ53PWjZk7GTfWJQiTksbtl1dJ3LMDV2+JNOxXebGFOApAcFwFwHCh1HP4b+WmUdTH/9IgluRDm76lWggfPAQo5wGN190YOsqfc7cb06R1T0YxxinfQyFoPdFgJyKHZ+t3XK2XRUAT1CU0sNb7h5ja7uhBBKPJFDqS1z0ztb/6nqXAIphDw17IpbxUfjdNvTa/s7oRMFJFOiS+SIHq235QrIadSMiQDQzfORaZnN2biOhkUaSa+iDXpjI7B+RXdOJR58veijLnQE5b6Y/2nXmSsgfHL/0+hX0gKY7GheKG/TCH/0UrsN6hwewILBxxZSaeQj/AQT+mrE4m+979oTjF85eRtfh710/97q73ZQRdfB5J7oGD8Q2/hsvyvMKhWPC6MMG2dRghONJE80Zs3Mxi9x3NvxzkcjG2Wmnhk5sUeUoniQsgGqGEvC7jjJwuwaOt7e8bDVwj20RKu5Mei1mVIWrEnVovsO7L6D0k5H41urfic6LwuaYRuS9tJnoB2tzUZgDaG6RqtiiWB/a6p4Tvnld0qHdm2STx0DSnWvNFvHEJDyFccpaQWgWLVj7kD2LIIcsV1L0mUu8D9FFGTpvXe0s5C4zs8fTT4wjaKrplPDF3+Luz4/wn853aEm/X9uImGZOqnA85ph1nzpmgnYRK+dfiHH5Avo=
